export const products = [
  // {
  //   id: 1,
  //   image: '/products/pexels-the-glorious-studio-3584518-10976653.jpg',
  //   name: 'Luxury Diamond Ring',
  //   description:
  //     'Every detail, from the sparkle of the diamonds to the elegant packaging.',
  //   price: 6720000,
  //   category: 'Rings',
  //   material: 'Diamond',
  //   rating: 4.9,
  //   stock: 2,
  //   tags: ['gold', 'luxury', 'ring', 'diamond'],
  // },
  // {
  //   id: 2,
  //   image: '/products/pexels-the-glorious-studio-3584518-10976654.jpg',
  //   name: 'Royal Diamond Earring',
  //   description:
  //     'From the moment I stepped into iDiamond, I felt like royalty.',
  //   price: 5250000,
  //   category: 'Earrings',
  //   material: 'Diamond',
  //   rating: 4.9,
  //   stock: 5,
  //   tags: ['gold', 'royal', 'earring', 'diamond'],
  // },
  // {
  //   id: 3,
  //   image: '/products/pexels-dauphotographer-30852235.jpg',
  //   name: 'Sparkling Diamond Bracelet',
  //   description:
  //     'Every detail, from the sparkle of the diamonds to the elegant packaging.',
  //   price: 3780000,
  //   category: 'Bracelets',
  //   material: 'Diamond',
  //   rating: 4.7,
  //   stock: 8,
  //   tags: ['diamond', 'platinum', 'sparkling', 'bracelet'],
  // },
  // {
  //   id: 4,
  //   image: '/products/pexels-the-glorious-studio-3584518-12026053.jpg',
  //   name: 'Exquisite Gold Bracelet',
  //   description:
  //     "Exceptional quality and outstanding service, doesn't just sell jewelry.",
  //   price: 3150000,
  //   category: 'Bracelets',
  //   material: 'Gold',
  //   rating: 4.6,
  //   stock: 12,
  //   tags: ['gold', 'exquisite', 'bracelet'],
  // },
  // {
  //   id: 5,
  //   image: '/products/pexels-the-glorious-studio-3584518-12026051.jpg',
  //   name: 'Classic Diamond Bracelet',
  //   description:
  //     'Absolutely breathtaking! The craftsmanship of my diamond ring.',
  //   price: 4200000,
  //   category: 'Bracelets',
  //   material: 'Diamond',
  //   rating: 4.5,
  //   stock: 7,
  //   tags: ['diamond', 'silver', 'classic', 'bracelet'],
  // },
  // {
  //   id: 7,
  //   image: '/products/pexels-the-glorious-studio-3584518-10475793.jpg',
  //   name: 'Elegant Diamond Ring',
  //   description:
  //     'Every detail, from the sparkle of the diamonds to the elegant packaging.',
  //   price: 6300000,
  //   category: 'Rings',
  //   material: 'Diamond',
  //   rating: 4.9,
  //   stock: 4,
  //   tags: ['diamond', 'platinum', 'elegant', 'ring'],
  // },
  // {
  //   id: 8,
  //   image: 'https://salve.co.in/cdn/shop/files/1680--1.jpg?v=1699445118',
  //   name: 'Chic Gold Earrings',
  //   description:
  //     "Exceptional quality and outstanding service, doesn't just sell jewelry.",
  //   price: 2940000,
  //   category: 'Earrings',
  //   material: 'Gold',
  //   rating: 4.7,
  //   stock: 9,
  //   tags: ['gold', 'chic', 'earrings'],
  // },
  // {
  //   id: 9,
  //   image: 'https://www.bsa-images.com/kormanfinejewelry/Inbox/170-01424.jpg',
  //   name: 'Timeless Diamond Bracelet',
  //   description:
  //     'Absolutely breathtaking! The craftsmanship of my diamond ring.',
  //   price: 5880000,
  //   category: 'Bracelets',
  //   material: 'Diamond',
  //   rating: 4.8,
  //   stock: 3,
  //   tags: ['diamond', 'platinum', 'timeless', 'bracelet'],
  // },
  // {
  //   id: 10,
  //   image:
  //     'https://www.my-jewellery.com/media/catalog/product/p/r/product_images-candy_charm_necklace-gold-front.jpg',
  //   name: 'Candy Charm Necklace',
  //   description:
  //     'From the moment I stepped into iDiamond, I felt like royalty.',
  //   price: 3570000,
  //   category: 'Necklaces',
  //   material: 'Gold',
  //   rating: 4.6,
  //   stock: 11,
  //   tags: ['gold', 'charm', 'necklace'],
  // },
  // {
  //   id: 11,
  //   image: 'https://i00.eu/img/413/1024x1024/dux13md5/63025.webp',
  //   name: 'Modern Diamond Ring',
  //   description:
  //     'Every detail, from the sparkle of the diamonds to the elegant packaging.',
  //   price: 3990000,
  //   category: 'Rings',
  //   material: 'Diamond',
  //   rating: 4.7,
  //   stock: 8,
  //   tags: ['diamond', 'silver', 'modern', 'ring'],
  // },
  // {
  //   id: 12,
  //   image: 'https://i00.eu/img/413/1024x1024/1ms8re61/41087.webp',
  //   name: 'Sophisticated Gold Necklace',
  //   description:
  //     "Exceptional quality and outstanding service, doesn't just sell jewelry.",
  //   price: 5460000,
  //   category: 'Necklaces',
  //   material: 'Gold',
  //   rating: 4.8,
  //   stock: 5,
  //   tags: ['gold', 'sophisticated', 'necklace'],
  // },
  // {
  //   id: 13,
  //   image:
  //     'https://images.laceandfavour.com/_cache/_products_main/1700x1700/ivory-and-co-dublin-gold-crystal-classic-pearl-drop-earrings-9395.webp',
  //   name: 'Classic Pearl Earrings',
  //   description:
  //     'Absolutely breathtaking! The craftsmanship of my diamond ring.',
  //   price: 3150000,
  //   category: 'Earrings',
  //   material: 'Pearl',
  //   rating: 4.5,
  //   stock: 10,
  //   tags: ['pearl', 'classic', 'earrings'],
  // },
  // {
  //   id: 14,
  //   image:
  //     'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw3f6ebefd/images/hi-res/50D3B4PNCAAA02_2.jpg?sw=640&sh=640',
  //   name: 'Elegant Diamond Pendant',
  //   description:
  //     'From the moment I stepped into iDiamond, I felt like royalty.',
  //   price: 4410000,
  //   category: 'Pendants',
  //   material: 'Platinum',
  //   rating: 4.7,
  //   stock: 6,
  //   tags: ['diamond', 'platinum', 'elegant', 'pendant'],
  // },

  // NEW DATAS
  // NEW DATAS
  // NEW DATAS

  // Bracelet Products
  {
    id: 16,
    image: '/bracelet/diamond-and-gold-bracelet.jpg',
    name: 'Diamond and Gold Bracelet',
    description:
      'A stunning combination of diamonds and gold creates this timeless bracelet that adds elegance to any outfit.',
    price: 4200000,
    category: 'Bracelets',
    material: 'Diamond, Gold',
    rating: 4.8,
    stock: 5,
    tags: ['diamond', 'gold', 'bracelet', 'elegant', 'timeless'],
  },
  {
    id: 17,
    image: '/bracelet/elegant-diamond-and-gold-bracelet.jpg',
    name: 'Elegant Diamond and Gold Bracelet',
    description:
      'Exquisite craftsmanship meets luxury design in this elegant diamond and gold bracelet that speaks of sophistication.',
    price: 5250000,
    category: 'Bracelets',
    material: 'Diamond, Gold',
    rating: 4.9,
    stock: 3,
    tags: ['diamond', 'gold', 'bracelet', 'elegant', 'luxury'],
  },
  {
    id: 18,
    image: '/bracelet/gold-bracelet-with-gems.jpg',
    name: 'Gold Bracelet with Gems',
    description:
      'Beautiful gold bracelet adorned with precious gems that catch the light and create a mesmerizing sparkle.',
    price: 3150000,
    category: 'Bracelets',
    material: 'Gold, Gems',
    rating: 4.6,
    stock: 8,
    tags: ['gold', 'gems', 'bracelet', 'sparkling', 'precious'],
  },
  {
    id: 19,
    image: '/bracelet/gold-bracelets-studded-with-diamonds.jpg',
    name: 'Gold Bracelets Studded with Diamonds',
    description:
      'Luxurious gold bracelets featuring carefully placed diamonds that create a dazzling display of brilliance.',
    price: 5880000,
    category: 'Bracelets',
    material: 'Gold, Diamond',
    rating: 4.9,
    stock: 4,
    tags: ['gold', 'diamond', 'bracelet', 'luxury', 'studded'],
  },
  {
    id: 20,
    image: '/bracelet/gold-bracelets-with-diamonds.jpg',
    name: 'Gold Bracelets with Diamonds',
    description:
      'Classic gold bracelets enhanced with the finest diamonds, perfect for both casual and formal occasions.',
    price: 4620000,
    category: 'Bracelets',
    material: 'Gold, Diamond',
    rating: 4.7,
    stock: 6,
    tags: ['gold', 'diamond', 'bracelet', 'classic', 'versatile'],
  },
  {
    id: 21,
    image: '/bracelet/silver-bracelet-with-diamond.jpg',
    name: 'Silver Bracelet with Diamond',
    description:
      'Elegant silver bracelet featuring a stunning diamond that adds a touch of sophistication to any ensemble.',
    price: 2940000,
    category: 'Bracelets',
    material: 'Silver, Diamond',
    rating: 4.5,
    stock: 10,
    tags: ['silver', 'diamond', 'bracelet', 'elegant', 'sophisticated'],
  },
  {
    id: 22,
    image: '/bracelet/silver-colored-bracelet-with-clear-gemstones.jpg',
    name: 'Silver Colored Bracelet with Clear Gemstones',
    description:
      'Beautiful silver-toned bracelet adorned with clear gemstones that create a subtle yet captivating sparkle.',
    price: 2100000,
    category: 'Bracelets',
    material: 'Silver, Gemstones',
    rating: 4.4,
    stock: 12,
    tags: ['silver', 'gemstones', 'bracelet', 'clear', 'subtle'],
  },

  // Earrings Products
  {
    id: 23,
    image: '/earrings/a-pair-of-gemstones-studded-earrings.jpg',
    name: 'A Pair of Gemstones Studded Earrings',
    description:
      'Exquisite pair of earrings featuring carefully selected gemstones that create a stunning display of color and light.',
    price: 2520000,
    category: 'Earrings',
    material: 'Gemstones, Gold',
    rating: 4.6,
    stock: 7,
    tags: ['gemstones', 'earrings', 'studded', 'colorful', 'elegant'],
  },
  {
    id: 24,
    image: '/earrings/captivating-rabbit-shaped-diamond-earrings.jpg',
    name: 'Captivating Rabbit Shaped Diamond Earrings',
    description:
      'Unique and charming rabbit-shaped earrings featuring brilliant diamonds that make a delightful statement piece.',
    price: 3360000,
    category: 'Earrings',
    material: 'Diamond, Gold',
    rating: 4.7,
    stock: 5,
    tags: ['diamond', 'earrings', 'rabbit-shaped', 'unique', 'charming'],
  },
  {
    id: 25,
    image: '/earrings/diamond-earrings-.jpg',
    name: 'Diamond Earrings',
    description:
      'Classic diamond earrings that showcase the natural beauty and brilliance of these precious stones.',
    price: 3780000,
    category: 'Earrings',
    material: 'Diamond, Platinum',
    rating: 4.8,
    stock: 8,
    tags: ['diamond', 'earrings', 'classic', 'brilliant', 'timeless'],
  },
  {
    id: 26,
    image: '/earrings/elegant-diamond-and-pearl-drop-earrings-.jpg',
    name: 'Elegant Diamond and Pearl Drop Earrings',
    description:
      'Sophisticated drop earrings combining the elegance of pearls with the sparkle of diamonds for a timeless look.',
    price: 3150000,
    category: 'Earrings',
    material: 'Diamond, Pearl, Gold',
    rating: 4.7,
    stock: 6,
    tags: ['diamond', 'pearl', 'earrings', 'drop', 'elegant'],
  },
  {
    id: 27,
    image: '/earrings/gold-earring-with-diamond.jpg',
    name: 'Gold Earring with Diamond',
    description:
      'Stunning gold earring featuring a beautiful diamond that adds a touch of luxury to any outfit.',
    price: 2940000,
    category: 'Earrings',
    material: 'Gold, Diamond',
    rating: 4.6,
    stock: 9,
    tags: ['gold', 'diamond', 'earring', 'luxury', 'beautiful'],
  },
  {
    id: 28,
    image: '/earrings/golden-earrings-with-diamond.jpg',
    name: 'Golden Earrings with Diamond',
    description:
      'Elegant golden earrings adorned with diamonds that create a perfect balance of warmth and sparkle.',
    price: 4200000,
    category: 'Earrings',
    material: 'Gold, Diamond',
    rating: 4.8,
    stock: 4,
    tags: ['gold', 'diamond', 'earrings', 'elegant', 'warm'],
  },
  {
    id: 29,
    image: '/earrings/precious-earrings-with-crystals.jpg',
    name: 'Precious Earrings with Crystals',
    description:
      'Beautiful earrings featuring precious metals and stunning crystals that create a mesmerizing light show.',
    price: 1890000,
    category: 'Earrings',
    material: 'Crystals, Gold',
    rating: 4.5,
    stock: 11,
    tags: ['crystals', 'earrings', 'precious', 'mesmerizing', 'beautiful'],
  },

  // Necklace Products
  {
    id: 30,
    image: '/necklace/diamond-pendant.jpg',
    name: 'Diamond Pendant',
    description:
      'Exquisite diamond pendant that serves as the perfect centerpiece for any necklace, radiating elegance and sophistication.',
    price: 2520000,
    category: 'Necklaces',
    material: 'Diamond, Gold',
    rating: 4.7,
    stock: 8,
    tags: ['diamond', 'pendant', 'elegant', 'sophisticated', 'centerpiece'],
  },
  {
    id: 31,
    image: '/necklace/elegant-diamond-flower-pendant-necklace.jpg',
    name: 'Elegant Diamond Flower Pendant Necklace',
    description:
      'Beautiful necklace featuring a delicate flower pendant adorned with diamonds, perfect for romantic occasions.',
    price: 3780000,
    category: 'Necklaces',
    material: 'Diamond, Gold',
    rating: 4.8,
    stock: 5,
    tags: ['diamond', 'flower', 'pendant', 'necklace', 'romantic'],
  },
  {
    id: 32,
    image: '/necklace/gold-necklace-with-diamonds.jpg',
    name: 'Gold Necklace with Diamonds',
    description:
      'Luxurious gold necklace featuring carefully placed diamonds that create a stunning display of brilliance and elegance.',
    price: 5460000,
    category: 'Necklaces',
    material: 'Gold, Diamond',
    rating: 4.9,
    stock: 3,
    tags: ['gold', 'diamond', 'necklace', 'luxury', 'brilliant'],
  },
  {
    id: 33,
    image: '/necklace/gold-necklace-with-padlock-pendant.jpg',
    name: 'Gold Necklace with Padlock Pendant',
    description:
      'Unique gold necklace featuring a stylish padlock pendant that symbolizes love and commitment.',
    price: 3150000,
    category: 'Necklaces',
    material: 'Gold',
    rating: 4.6,
    stock: 7,
    tags: ['gold', 'padlock', 'pendant', 'necklace', 'symbolic'],
  },
  {
    id: 34,
    image: '/necklace/gold-necklace-with-round-pendant.jpg',
    name: 'Gold Necklace with Round Pendant',
    description:
      'Classic gold necklace with a beautiful round pendant that adds a touch of elegance to any outfit.',
    price: 2940000,
    category: 'Necklaces',
    material: 'Gold',
    rating: 4.5,
    stock: 9,
    tags: ['gold', 'round', 'pendant', 'necklace', 'classic'],
  },
  {
    id: 35,
    image: '/necklace/gold-necklace-with-shiny-beads-on-the-pendant.jpg',
    name: 'Gold Necklace with Shiny Beads on the Pendant',
    description:
      'Stunning gold necklace featuring a pendant adorned with shiny beads that create a beautiful light effect.',
    price: 2520000,
    category: 'Necklaces',
    material: 'Gold, Beads',
    rating: 4.4,
    stock: 10,
    tags: ['gold', 'beads', 'pendant', 'necklace', 'shiny'],
  },
  {
    id: 36,
    image: '/necklace/silver-and-green-gemstone-necklace.jpg',
    name: 'Silver and Green Gemstone Necklace',
    description:
      'Beautiful silver necklace featuring green gemstones that create a natural and refreshing aesthetic.',
    price: 2100000,
    category: 'Necklaces',
    material: 'Silver, Gemstones',
    rating: 4.5,
    stock: 12,
    tags: ['silver', 'green', 'gemstones', 'necklace', 'natural'],
  },
  {
    id: 37,
    image: '/necklace/silver-diamond-studded-pendant-necklace.jpg',
    name: 'Silver Diamond Studded Pendant Necklace',
    description:
      'Elegant silver necklace with a pendant studded with diamonds that creates a sophisticated and luxurious look.',
    price: 3360000,
    category: 'Necklaces',
    material: 'Silver, Diamond',
    rating: 4.7,
    stock: 6,
    tags: ['silver', 'diamond', 'pendant', 'necklace', 'sophisticated'],
  },
  {
    id: 38,
    image: '/necklace/silver-necklace-with-a-heart-shaped-pendant.jpg',
    name: 'Silver Necklace with a Heart Shaped Pendant',
    description:
      'Romantic silver necklace featuring a heart-shaped pendant that makes a perfect gift for loved ones.',
    price: 1890000,
    category: 'Necklaces',
    material: 'Silver',
    rating: 4.6,
    stock: 8,
    tags: ['silver', 'heart', 'pendant', 'necklace', 'romantic'],
  },

  // Ring Products
  {
    id: 39,
    image: '/ring/elegant-emerald-and-diamond-ring-.jpg',
    name: 'Elegant Emerald and Diamond Ring',
    description:
      'Stunning ring featuring the rich green of emeralds combined with the brilliance of diamonds for a truly elegant piece.',
    price: 4620000,
    category: 'Rings',
    material: 'Emerald, Diamond, Gold',
    rating: 4.8,
    stock: 4,
    tags: ['emerald', 'diamond', 'ring', 'elegant', 'green'],
  },
  {
    id: 40,
    image:
      '/ring/elegant-gold-ring-with-precious-stones-on-black-background.jpg',
    name: 'Elegant Gold Ring with Precious Stones on Black Background',
    description:
      'Sophisticated gold ring adorned with precious stones that stand out beautifully against any background.',
    price: 3780000,
    category: 'Rings',
    material: 'Gold, Precious Stones',
    rating: 4.7,
    stock: 6,
    tags: ['gold', 'precious-stones', 'ring', 'sophisticated', 'elegant'],
  },
  {
    id: 41,
    image: '/ring/elegant-ruby-and-diamond-silver-ring-.jpg',
    name: 'Elegant Ruby and Diamond Silver Ring',
    description:
      'Beautiful silver ring featuring the deep red of rubies combined with sparkling diamonds for a classic look.',
    price: 4200000,
    category: 'Rings',
    material: 'Ruby, Diamond, Silver',
    rating: 4.8,
    stock: 5,
    tags: ['ruby', 'diamond', 'silver', 'ring', 'classic'],
  },
  {
    id: 42,
    image: '/ring/engagement-ring-with-silver-and-diamond.jpg',
    name: 'Engagement Ring with Silver and Diamond',
    description:
      'Perfect engagement ring featuring a stunning diamond set in elegant silver, symbolizing eternal love and commitment.',
    price: 5460000,
    category: 'Engagement Rings',
    material: 'Diamond, Silver',
    rating: 4.9,
    stock: 3,
    tags: ['engagement', 'diamond', 'silver', 'ring', 'eternal'],
  },
  {
    id: 43,
    image: '/ring/gold-engagement-ring-with-diamond.jpg',
    name: 'Gold Engagement Ring with Diamond',
    description:
      'Timeless gold engagement ring featuring a brilliant diamond that represents the beginning of a beautiful journey together.',
    price: 6300000,
    category: 'Engagement Rings',
    material: 'Gold, Diamond',
    rating: 4.9,
    stock: 2,
    tags: ['engagement', 'gold', 'diamond', 'ring', 'timeless'],
  },
  {
    id: 44,
    image: '/ring/gold-ring-with-diamonds.jpg',
    name: 'Gold Ring with Diamonds',
    description:
      'Elegant gold ring adorned with diamonds that create a stunning display of luxury and sophistication.',
    price: 4620000,
    category: 'Rings',
    material: 'Gold, Diamond',
    rating: 4.8,
    stock: 7,
    tags: ['gold', 'diamond', 'ring', 'elegant', 'luxury'],
  },
  {
    id: 45,
    image: '/ring/gold-rings.jpg',
    name: 'Gold Rings',
    description:
      'Classic gold rings that showcase the natural beauty and warmth of this precious metal.',
    price: 1890000,
    category: 'Rings',
    material: 'Gold',
    rating: 4.5,
    stock: 15,
    tags: ['gold', 'rings', 'classic', 'warm', 'timeless'],
  },
  {
    id: 46,
    image: '/ring/gold-wedding-ring.jpg',
    name: 'Gold Wedding Ring',
    description:
      'Traditional gold wedding ring that symbolizes love, commitment, and the promise of forever.',
    price: 2520000,
    category: 'Wedding Rings',
    material: 'Gold',
    rating: 4.7,
    stock: 10,
    tags: ['gold', 'wedding', 'ring', 'traditional', 'commitment'],
  },
  {
    id: 47,
    image: '/ring/luxurious-emerald-cut-ring-with-diamond-accents.jpg',
    name: 'Luxurious Emerald Cut Ring with Diamond Accents',
    description:
      'Luxurious ring featuring an emerald-cut stone with diamond accents that create a sophisticated and elegant appearance.',
    price: 5880000,
    category: 'Rings',
    material: 'Emerald, Diamond, Gold',
    rating: 4.9,
    stock: 3,
    tags: ['emerald', 'diamond', 'ring', 'luxurious', 'sophisticated'],
  },
  {
    id: 48,
    image: '/ring/silver-and-diamonds-ring.jpg',
    name: 'Silver and Diamonds Ring',
    description:
      'Beautiful silver ring featuring diamonds that create a perfect balance of elegance and sparkle.',
    price: 3360000,
    category: 'Rings',
    material: 'Silver, Diamond',
    rating: 4.6,
    stock: 8,
    tags: ['silver', 'diamond', 'ring', 'elegant', 'sparkle'],
  },
  {
    id: 49,
    image: '/ring/silver-engagement-ring.jpg',
    name: 'Silver Engagement Ring',
    description:
      'Elegant silver engagement ring that offers a modern and sophisticated alternative to traditional gold.',
    price: 2940000,
    category: 'Engagement Rings',
    material: 'Silver',
    rating: 4.7,
    stock: 6,
    tags: ['silver', 'engagement', 'ring', 'modern', 'sophisticated'],
  },
  {
    id: 50,
    image: '/ring/silver-floral-ring-with-diamonds.jpg',
    name: 'Silver Floral Ring with Diamonds',
    description:
      'Delicate silver ring featuring a beautiful floral design adorned with diamonds for a romantic and elegant look.',
    price: 3780000,
    category: 'Rings',
    material: 'Silver, Diamond',
    rating: 4.8,
    stock: 5,
    tags: ['silver', 'floral', 'diamond', 'ring', 'romantic'],
  },
  {
    id: 51,
    image: '/ring/silver-wedding-ring-with-diamond.jpg',
    name: 'Silver Wedding Ring with Diamond',
    description:
      'Modern silver wedding ring featuring a diamond that adds a touch of luxury to this symbol of eternal love.',
    price: 4200000,
    category: 'Wedding Rings',
    material: 'Silver, Diamond',
    rating: 4.8,
    stock: 4,
    tags: ['silver', 'wedding', 'diamond', 'ring', 'modern'],
  },
  {
    id: 52,
    image: '/ring/silver-wedding-ring.jpg',
    name: 'Silver Wedding Ring',
    description:
      'Classic silver wedding ring that represents the purity and strength of love and commitment.',
    price: 2100000,
    category: 'Wedding Rings',
    material: 'Silver',
    rating: 4.6,
    stock: 12,
    tags: ['silver', 'wedding', 'ring', 'classic', 'pure'],
  },

  // Additional Products from Renamed Images
  {
    id: 53,
    image: '/wr.jpg',
    name: 'White Rose Diamond Ring',
    description:
      'Exquisite white rose-inspired diamond ring that symbolizes pure love and eternal beauty.',
    price: 3780000,
    category: 'Rings',
    material: 'Diamond, White Gold',
    rating: 4.8,
    stock: 6,
    tags: ['diamond', 'white-gold', 'ring', 'rose-inspired', 'elegant'],
  },
  {
    id: 54,
    image: '/silver-wedding-rings.jpg',
    name: 'Silver Wedding Rings Set',
    description:
      'Beautiful matching set of silver wedding rings that represent the unity and commitment of marriage.',
    price: 2520000,
    category: 'Wedding Rings',
    material: 'Silver',
    rating: 4.7,
    stock: 8,
    tags: ['silver', 'wedding', 'rings', 'matching-set', 'unity'],
  },
  {
    id: 55,
    image: '/gold-wedding-rings.jpg',
    name: 'Gold Wedding Rings Collection',
    description:
      'Timeless collection of gold wedding rings that embody tradition, love, and everlasting commitment.',
    price: 4200000,
    category: 'Wedding Rings',
    material: 'Gold',
    rating: 4.9,
    stock: 5,
    tags: ['gold', 'wedding', 'rings', 'timeless', 'traditional'],
  },
  {
    id: 56,
    image: '/e-r.jpg',
    name: 'Emerald Ruby Ring',
    description:
      'Stunning ring featuring the perfect combination of emerald and ruby stones for a bold and elegant statement.',
    price: 4620000,
    category: 'Rings',
    material: 'Emerald, Ruby, Gold',
    rating: 4.8,
    stock: 4,
    tags: ['emerald', 'ruby', 'ring', 'bold', 'elegant'],
  },
  {
    id: 57,
    image: '/er.jpg',
    name: 'Elegant Ruby Ring',
    description:
      'Sophisticated ruby ring that captures the essence of passion and luxury with its deep red brilliance.',
    price: 3360000,
    category: 'Rings',
    material: 'Ruby, Gold',
    rating: 4.7,
    stock: 7,
    tags: ['ruby', 'ring', 'passion', 'luxury', 'sophisticated'],
  },
  {
    id: 58,
    image: '/engagementring.jpg',
    name: 'Classic Engagement Ring',
    description:
      'Timeless engagement ring featuring a brilliant center stone that symbolizes the beginning of forever.',
    price: 5460000,
    category: 'Engagement Rings',
    material: 'Diamond, Platinum',
    rating: 4.9,
    stock: 3,
    tags: ['engagement', 'diamond', 'ring', 'timeless', 'forever'],
  },
  {
    id: 59,
    image: '/engagement-ring.jpg',
    name: 'Premium Engagement Ring',
    description:
      'Exquisite engagement ring with exceptional craftsmanship and the finest diamonds for the perfect proposal.',
    price: 6300000,
    category: 'Engagement Rings',
    material: 'Diamond, White Gold',
    rating: 4.9,
    stock: 2,
    tags: ['engagement', 'diamond', 'ring', 'premium', 'exquisite'],
  },
  {
    id: 60,
    image: '/elegant-gold-wedding-ring.jpg',
    name: 'Elegant Gold Wedding Ring',
    description:
      'Sophisticated gold wedding ring with intricate detailing that represents the elegance of true love.',
    price: 2940000,
    category: 'Wedding Rings',
    material: 'Gold',
    rating: 4.8,
    stock: 9,
    tags: ['gold', 'wedding', 'ring', 'elegant', 'intricate'],
  },
  {
    id: 61,
    image: '/e_r.jpg',
    name: 'Emerald Diamond Ring',
    description:
      'Beautiful ring combining the rich green of emeralds with the sparkle of diamonds for a unique and elegant piece.',
    price: 4200000,
    category: 'Rings',
    material: 'Emerald, Diamond, Gold',
    rating: 4.7,
    stock: 6,
    tags: ['emerald', 'diamond', 'ring', 'unique', 'elegant'],
  },
  {
    id: 62,
    image: '/diamond-engagement-ring.jpg',
    name: 'Diamond Engagement Ring',
    description:
      'Stunning diamond engagement ring that captures the perfect moment with its exceptional brilliance and beauty.',
    price: 5880000,
    category: 'Engagement Rings',
    material: 'Diamond, Platinum',
    rating: 4.9,
    stock: 4,
    tags: ['diamond', 'engagement', 'ring', 'brilliant', 'perfect'],
  },
];
