export const products = [
  {
    id: 1,
    image: '/products/pexels-the-glorious-studio-3584518-10976653.jpg',
    name: 'Luxury Diamond Ring',
    description:
      'Every detail, from the sparkle of the diamonds to the elegant packaging.',
    price: 3200,
    category: 'Bracelets',
    material: 'Gold',
    rating: 4.9,
    stock: 2,
    tags: ['gold', 'luxury', 'bracelet'],
  },
  {
    id: 2,
    image: '/products/pexels-the-glorious-studio-3584518-10976654.jpg',
    name: 'Royal Diamond Earring',
    description:
      'From the moment I stepped into iDiamond, I felt like royalty.',
    price: 2500,
    category: 'Necklaces',
    material: 'Pearl',
    rating: 4.9,
    stock: 5,
    tags: ['pearl', 'royal', 'luxury'],
  },
  {
    id: 3,
    image: '/products/pexels-dauphotographer-30852235.jpg',
    name: 'Sparkling Diamond Bracelet',
    description:
      'Every detail, from the sparkle of the diamonds to the elegant packaging.',
    price: 1800,
    category: 'Earrings',
    material: 'Platinum',
    rating: 4.7,
    stock: 8,
    tags: ['diamond', 'platinum', 'sparkling'],
  },
  {
    id: 4,
    image: '/products/pexels-the-glorious-studio-3584518-12026053.jpg',
    name: 'Exquisite Gold Bracelet',
    description:
      "Exceptional quality and outstanding service, doesn't just sell jewelry.",
    price: 1500,
    category: 'Bracelets',
    material: 'Gold',
    rating: 4.6,
    stock: 12,
    tags: ['gold', 'exquisite', 'bracelet'],
  },
  {
    id: 5,
    image: '/products/pexels-the-glorious-studio-3584518-12026051.jpg',
    name: 'Classic Diamond Bracelet',
    description:
      'Absolutely breathtaking! The craftsmanship of my diamond ring.',
    price: 2000,
    category: 'Pendants',
    material: 'Silver',
    rating: 4.5,
    stock: 7,
    tags: ['diamond', 'silver', 'classic'],
  },
  {
    id: 7,
    image: '/products/pexels-the-glorious-studio-3584518-10475793.jpg',
    name: 'Elegant Diamond Ring',
    description:
      'Every detail, from the sparkle of the diamonds to the elegant packaging.',
    price: 3000,
    category: 'Necklaces',
    material: 'Platinum',
    rating: 4.9,
    stock: 4,
    tags: ['diamond', 'platinum', 'elegant'],
  },
  {
    id: 8,
    image: 'https://salve.co.in/cdn/shop/files/1680--1.jpg?v=1699445118',
    name: 'Chic Gold Earrings',
    description:
      "Exceptional quality and outstanding service, doesn't just sell jewelry.",
    price: 1400,
    category: 'Earrings',
    material: 'Gold',
    rating: 4.7,
    stock: 9,
    tags: ['gold', 'chic', 'earrings'],
  },
  {
    id: 9,
    image: 'https://www.bsa-images.com/kormanfinejewelry/Inbox/170-01424.jpg',
    name: 'Timeless Diamond Bracelet',
    description:
      'Absolutely breathtaking! The craftsmanship of my diamond ring.',
    price: 2800,
    category: 'Bracelets',
    material: 'Platinum',
    rating: 4.8,
    stock: 3,
    tags: ['diamond', 'platinum', 'timeless'],
  },
  {
    id: 10,
    image:
      'https://www.my-jewellery.com/media/catalog/product/p/r/product_images-candy_charm_necklace-gold-front.jpg',
    name: 'Candy Charm Necklacek',
    description:
      'From the moment I stepped into iDiamond, I felt like royalty.',
    price: 1700,
    category: 'Necklaces',
    material: 'Gold',
    rating: 4.6,
    stock: 11,
    tags: ['gold', 'charm', 'necklace'],
  },
  {
    id: 11,
    image: 'https://i00.eu/img/413/1024x1024/dux13md5/63025.webp',
    name: 'Modern Diamond Ring',
    description:
      'Every detail, from the sparkle of the diamonds to the elegant packaging.',
    price: 1900,
    category: 'Rings',
    material: 'Silver',
    rating: 4.7,
    stock: 8,
    tags: ['diamond', 'silver', 'modern'],
  },
  {
    id: 12,
    image: 'https://i00.eu/img/413/1024x1024/1ms8re61/41087.webp',
    name: 'Sophisticated Gold Necklace',
    description:
      "Exceptional quality and outstanding service, doesn't just sell jewelry.",
    price: 2600,
    category: 'Necklaces',
    material: 'Gold',
    rating: 4.8,
    stock: 5,
    tags: ['gold', 'sophisticated', 'necklace'],
  },
  {
    id: 13,
    image:
      'https://images.laceandfavour.com/_cache/_products_main/1700x1700/ivory-and-co-dublin-gold-crystal-classic-pearl-drop-earrings-9395.webp',
    name: 'Classic Pearl Earrings',
    description:
      'Absolutely breathtaking! The craftsmanship of my diamond ring.',
    price: 1500,
    category: 'Earrings',
    material: 'Pearl',
    rating: 4.5,
    stock: 10,
    tags: ['pearl', 'classic', 'earrings'],
  },
  {
    id: 14,
    image:
      'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw3f6ebefd/images/hi-res/50D3B4PNCAAA02_2.jpg?sw=640&sh=640',
    name: 'Elegant Diamond Pendant',
    description:
      'From the moment I stepped into iDiamond, I felt like royalty.',
    price: 2100,
    category: 'Pendants',
    material: 'Platinum',
    rating: 4.7,
    stock: 6,
    tags: ['diamond', 'platinum', 'elegant'],
  },
];
