import type { Metadata } from 'next';
// import localFont from "next/font/local";
import { DM_Sans, Playfair_Display } from 'next/font/google';
import './globals.css';
import { ShoppingCartProvider } from '@/context/ShoppingCartContext';
import { Toaster } from 'sonner';

const dmSans = DM_Sans({
  subsets: ['latin'],
  variable: '--font-dm-sans',
  weight: ['400', '500', '700'],
});

const playfairDisplay = Playfair_Display({
  subsets: ['latin'],
  variable: '--font-playfair-display',
  weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${dmSans.variable} ${playfairDisplay.variable} antialiased bg-white text-dark-brown`}
      >
        <ShoppingCartProvider>
          <Toaster position='top-center' />
          <main>{children}</main>
        </ShoppingCartProvider>
      </body>
    </html>
  );
}
