export const products = [
  {
    id: 1,
    image: "/products/pexels-the-glorious-studio-3584518-10976653.jpg",
    name: "Luxury Diamond Ring",
    description:
      "Every detail, from the sparkle of the diamonds to the elegant packaging.",
    price: 3200,
    category: "Bracelets",
    material: "Gold",
    rating: 4.9,
    stock: 2,
    tags: ["gold", "luxury", "bracelet"],
  },
  {
    id: 2,
    image: "/products/pexels-the-glorious-studio-3584518-10976654.jpg",
    name: "Royal Pearl Necklace",
    description:
      "From the moment I stepped into iDiamond, I felt like royalty.",
    price: 2500,
    category: "Necklaces",
    material: "Pearl",
    rating: 4.9,
    stock: 5,
    tags: ["pearl", "royal", "luxury"],
  },
  {
    id: 3,
    image: "/products/pexels-dauphotographer-30852235.jpg",
    name: "Sparkling Diamond Bracelet",
    description:
      "Every detail, from the sparkle of the diamonds to the elegant packaging.",
    price: 1800,
    category: "Earrings",
    material: "Platinum",
    rating: 4.7,
    stock: 8,
    tags: ["diamond", "platinum", "sparkling"],
  },
  {
    id: 4,
    image: "/products/pexels-the-glorious-studio-3584518-12026053.jpg",
    name: "Exquisite Gold Bracelet",
    description:
      "Exceptional quality and outstanding service, doesn't just sell jewelry.",
    price: 1500,
    category: "Bracelets",
    material: "Gold",
    rating: 4.6,
    stock: 12,
    tags: ["gold", "exquisite", "bracelet"],
  },
  {
    id: 5,
    image: "/products/pexels-the-glorious-studio-3584518-12026051.jpg",
    name: "Classic Diamond Pendant",
    description:
      "Absolutely breathtaking! The craftsmanship of my diamond ring.",
    price: 2000,
    category: "Pendants",
    material: "Silver",
    rating: 4.5,
    stock: 7,
    tags: ["diamond", "silver", "classic"],
  },
  {
    id: 6,
    image: "/products/pexels-n-voitkevich-8100396.jpg",
    name: "Luxury Pearl Ring",
    description:
      "From the moment I stepped into iDiamond, I felt like royalty.",
    price: 2200,
    category: "Rings",
    material: "Pearl",
    rating: 4.8,
    stock: 6,
    tags: ["pearl", "luxury", "ring"],
  },
  {
    id: 7,
    image: "/products/pexels-the-glorious-studio-3584518-10475793.jpg",
    name: "Elegant Diamond Necklace",
    description:
      "Every detail, from the sparkle of the diamonds to the elegant packaging.",
    price: 3000,
    category: "Necklaces",
    material: "Platinum",
    rating: 4.9,
    stock: 4,
    tags: ["diamond", "platinum", "elegant"],
  },
  {
    id: 8,
    image: "/products/pexels-anntarazevich-6614303.jpg",
    name: "Chic Gold Earrings",
    description:
      "Exceptional quality and outstanding service, doesn't just sell jewelry.",
    price: 1400,
    category: "Earrings",
    material: "Gold",
    rating: 4.7,
    stock: 9,
    tags: ["gold", "chic", "earrings"],
  },
  {
    id: 9,
    image: "/products/pexels-the-glorious-studio-3584518-10983778.jpg",
    name: "Timeless Diamond Bracelet",
    description:
      "Absolutely breathtaking! The craftsmanship of my diamond ring.",
    price: 2800,
    category: "Bracelets",
    material: "Platinum",
    rating: 4.8,
    stock: 3,
    tags: ["diamond", "platinum", "timeless"],
  },
  {
    id: 10,
    image: "/products/pexels-tima-miroshnichenko-6263101.jpg",
    name: "Vintage Pearl Pendant",
    description:
      "From the moment I stepped into iDiamond, I felt like royalty.",
    price: 1700,
    category: "Pendants",
    material: "Pearl",
    rating: 4.6,
    stock: 11,
    tags: ["pearl", "vintage", "pendant"],
  },
  {
    id: 11,
    image: "/products/pexels-cottonbro-9429420.jpg",
    name: "Modern Diamond Ring",
    description:
      "Every detail, from the sparkle of the diamonds to the elegant packaging.",
    price: 1900,
    category: "Rings",
    material: "Silver",
    rating: 4.7,
    stock: 8,
    tags: ["diamond", "silver", "modern"],
  },
  {
    id: 12,
    image: "/products/pexels-enginakyurt-1458867.jpg",
    name: "Sophisticated Gold Necklace",
    description:
      "Exceptional quality and outstanding service, doesn't just sell jewelry.",
    price: 2600,
    category: "Necklaces",
    material: "Gold",
    rating: 4.8,
    stock: 5,
    tags: ["gold", "sophisticated", "necklace"],
  },
  {
    id: 13,
    image: "/products/pexels-say-straight-1400349-2735970.jpg",
    name: "Classic Pearl Earrings",
    description:
      "Absolutely breathtaking! The craftsmanship of my diamond ring.",
    price: 1500,
    category: "Earrings",
    material: "Pearl",
    rating: 4.5,
    stock: 10,
    tags: ["pearl", "classic", "earrings"],
  },
  {
    id: 14,
    image: "/products/pexels-nimblevideoproductions-3091638.jpg",
    name: "Elegant Diamond Pendant",
    description:
      "From the moment I stepped into iDiamond, I felt like royalty.",
    price: 2100,
    category: "Pendants",
    material: "Platinum",
    rating: 4.7,
    stock: 6,
    tags: ["diamond", "platinum", "elegant"],
  },
];
